services:
  rag:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
     - REDIS_URL=redis://redis:6379/0
     - RABBITMQ_URL= amqp://$(RABBITMQ_USER):$(RABBIT_PASSWORD)@rabbitmq:5672/
    volumes:
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
    depends_on:
      redis:
        condition: service_healty
    restart: unless-stopped
  
  worker:
    build: .
    command: python worker.py
    env_file:
     - .env
    envionment:
     - REDIS_URL=redis://redis:6379/0
     - RABBITMQ_URL= amqp://$(RABBITMQ_USER):$(RABBIT_PASSWORD)@rabbitmq:5672/
    volumes:
     - ./data:/app/data
     - ./chroma_db:/app/chroma_db
    
    depends_on:
      redis:
        condition: service_healty
      rabbitmq:
        condition: service_healty
    restart: unless-stopped

  
  redis:
    image: redis/redis-stack-server:latest
    ports:
     - '6379:6379'
    volumes:
     - redis_data:/data
    healthchech:
      test: ['CMD','redis-cli','ping']
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    environment:
     - RABBITMQ_DEFAULT_USER=$(RABBITMQ_USER)
     - RABBITMQ_DEFAULT_PASS=$(RABBITMQ_PASSWORD)
    ports:
     - '5672:5672'
     - '15672:15672'
    volumes:
     - rabbitmq_data:/var/lib/rabbitmq
    healthchechk:
      test: ["CMD","rabbitmq-diaqnostics","-q","ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  redis_data:
  rabbitmq_data:
